version: '3.7'

services:
  twitter-consumer:
    container_name: twitter-consumer
    networks:
      - docker_twitter-network
    build: ./../.
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVER_PORT: 8080
      TWITTER_ELASTICSEARCH_HOSTS: es01:9200
    ports: [8082:8080]

networks:
  docker_twitter-network:
    external: true
