version: '3.7'

services:

# postgres db for shedlock
  postgres:
    image: postgres:12.1
    networks:
      - twitter-network
    container_name: "twitter-indexer-postgres"
    environment:
      POSTGRES_USER: twitter-indexer
      POSTGRES_PASSWORD: twitter-indexer
      POSTGRES_DB: twitter-indexer
    ports:
      - "5433:5432"
# graphite-grafana for metrics
  graphite-grafana:
    image: kamon/grafana_graphite:3.0
    networks:
      - twitter-network
    container_name: graphite
    ports:
      - "81:80"
      - "2003:2003"
# kafka
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - twitter-network
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    networks:
      - twitter-network
    container_name: kafka
    environment:
      KAFKA_MESSAGE_MAX_BYTES: 32768
      KAFKA_CREATE_TOPICS: "twitter-domain-event"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"

networks:
  twitter-network:
    driver: bridge
