version: '3.7'

services:

# postgres db for shedlock
  postgres:
    image: postgres:12.1
    container_name: "twitter-indexer-postgres"
    networks:
      - twitter-network
    environment:
      POSTGRES_USER: twitter-indexer
      POSTGRES_PASSWORD: twitter-indexer
      POSTGRES_DB: twitter-indexer
    ports:
      - "5433:5432"
# graphite-grafana for metrics
  graphite-grafana:
    image: kamon/grafana_graphite:3.0
    container_name: graphite
    networks:
      - twitter-network
    ports:
      - "81:80"
      - "2003:2003"
# kafka
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - twitter-network
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    networks:
      - twitter-network
    environment:
      KAFKA_MESSAGE_MAX_BYTES: 32768
      KAFKA_CREATE_TOPICS: "twitter-domain-event"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"

  twitter-indexer:
    container_name: twitter-indexer
    networks:
      - twitter-network
    build: ./../.
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      TWITTER_INDEXER_CONSUMER_KEY:
      TWITTER_INDEXER_CONSUMER_SECRET:
      TWITTER_INDEXER_TOKEN:
      TWITTER_INDEXER_SECRET:
      TWITTER_INDEXER_JOB_ENABLED: "true"
      TWITTER_INDEXER_CAPACITY:  10
      DB_HOST: twitter-indexer-postgres
      DB_PORT: 5433
      DB_NAME: twitter-indexer
      DB_USERNAME: twitter-indexer
      DB_PASSWORD: twitter-indexer
      GRAPHITE_HOST: graphite
      GRAPHITE_PORT: 2003
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
       - postgres

networks:
  twitter-network:
    driver: bridge
