spring:
  application:
    name: twitter-indexer-consumer
    version: '@version@'

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

  elasticsearch:
    rest:
      uris: ${TWITTER_ELASTICSEARCH_HOSTS:localhost:9200}

twitter:
  consumer:
    kafka:
      topic: twitter-domain-event
management:
  metrics.export.graphite:
    host: ${GRAPHITE_HOST:localhost}
    port: ${GRAPHITE_PORT:2003}
    global-prefix: ${spring.application.name}
    protocol: PLAINTEXT
    step: 10s

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    io.twitterconsumer.service: DEBUG
